### ISSUE TITLE
How to replace all user input to work with mobile inputs 

### ISSUE THREAD

**Issue by stickylabdev** [nanomachines/filibusters-game#528]
please help me how to change all stuff to work in mobile android device

**Comment by scottnm** [comment]
Input for the game wasn't designed with mobile in mind, so I'm not sure what the best control scheme would be for this game. If you wanted to tackle that problem yourself, the place to start working would be in the InputWrapper.cs file. If you could just abstract that functionality so that it works whether you're on PC or mobile then everything else should fall into place nicely and we'd be happy to accept a pull request with that change
